<?php
/**
 * Template for rendering Business Strategist recommendation shortcode
 *
 * @package    Vortex_AI_Marketplace
 * @subpackage Vortex_AI_Marketplace/public/partials/shortcodes
 */

// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}
?>

<div class="vortex-strategy-recommendation">
    <div class="vortex-strategy-header">
        <div class="vortex-strategy-title">
            <h3>
                <span class="vortex-strategy-icon dashicons dashicons-chart-bar"></span>
                <?php echo esc_html__('Business Strategist Recommendations', 'vortex-ai-marketplace'); ?>
                <?php if (!empty($focus)): ?>
                    <span class="vortex-strategy-focus">: <?php echo esc_html(ucfirst($focus)); ?></span>
                <?php endif; ?>
            </h3>
            <p class="vortex-strategy-subtitle"><?php echo esc_html__('AI-powered business optimization strategies', 'vortex-ai-marketplace'); ?></p>
        </div>
    </div>
    
    <?php if (empty($recommendations)): ?>
        <div class="vortex-strategy-empty">
            <p><?php echo esc_html__('No recommendations available for this focus area.', 'vortex-ai-marketplace'); ?></p>
        </div>
    <?php else: ?>
        <div class="vortex-strategy-recommendations">
            <?php foreach ($recommendations as $index => $recommendation): ?>
                <div class="vortex-strategy-item">
                    <div class="vortex-strategy-item-header">
                        <div class="vortex-strategy-item-number"><?php echo esc_html($index + 1); ?></div>
                        <h4 class="vortex-strategy-item-title"><?php echo esc_html($recommendation['title']); ?></h4>
                        
                        <div class="vortex-strategy-metrics">
                            <div class="vortex-strategy-metric vortex-strategy-impact <?php echo esc_attr('impact-' . $recommendation['impact']); ?>">
                                <span class="vortex-strategy-metric-label"><?php echo esc_html__('Impact', 'vortex-ai-marketplace'); ?></span>
                                <span class="vortex-strategy-metric-value"><?php echo esc_html(ucfirst($recommendation['impact'])); ?></span>
                            </div>
                            
                            <div class="vortex-strategy-metric vortex-strategy-implementation <?php echo esc_attr('implementation-' . $recommendation['implementation']); ?>">
                                <span class="vortex-strategy-metric-label"><?php echo esc_html__('Effort', 'vortex-ai-marketplace'); ?></span>
                                <span class="vortex-strategy-metric-value"><?php echo esc_html(ucfirst($recommendation['implementation'])); ?></span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="vortex-strategy-item-body">
                        <p class="vortex-strategy-item-description"><?php echo esc_html($recommendation['description']); ?></p>
                        
                        <?php if (!empty($recommendation['data'])): ?>
                            <div class="vortex-strategy-data">
                                <h5 class="vortex-strategy-data-title"><?php echo esc_html__('Projected Outcomes', 'vortex-ai-marketplace'); ?></h5>
                                <ul class="vortex-strategy-data-list">
                                    <?php foreach ($recommendation['data'] as $key => $value): ?>
                                        <li class="vortex-strategy-data-item">
                                            <span class="vortex-strategy-data-label"><?php echo esc_html(str_replace('_', ' ', ucfirst($key))); ?>:</span>
                                            <span class="vortex-strategy-data-value"><?php echo esc_html($value); ?></span>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
    <div class="vortex-strategy-footer">
        <p class="vortex-strategy-disclaimer">
            <?php echo esc_html__('Recommendations are generated by our Business Strategist AI based on marketplace data analysis.', 'vortex-ai-marketplace'); ?>
        </p>
    </div>
</div> 